### ISSUE TITLE
Duplicate files copied in APK lib/armeabi-v7a/libgnu

### ISSUE THREAD

**Issue by Selvamhibiz** [agenthunt/react-native-mailcore#4] opened 2018-05-04 10:51 UTC
Hi,

I am unable to run my react native Android project after installing mail core npm. It fails building the app and show the following error, "Duplicate files copied in APK lib/armeabi-v7a/libgnu". Any body faced this issue earlier. Need help on how to fix this issue.

I have cleared my build cache folder. still the issue exists.

**Comment by agenthunt** [comment] 2018-05-04 21:42
Hi @Selvamhibiz ,
Have you tried the `def deleteDuplicateJniFiles() {` solution mentioned in the README ?

**Comment by Selvamhibiz** [comment] 2018-05-06 05:55
Hi @agenthunt ,
Yes, i have defined def deleteDuplicateJnFiles() in the app/build.gradle file. The process which i follow is mentioned below:

1. I have install the react native mailcore package.

2.Link it to my project folder.

3.Copy paste the following lines in to settings.gradle
    include ':mailcore2-android-4'
    project(':mailcore2-android-4').projectDir = new File(rootProject.projectDir, '../node_modules/react- 
    native-mailcore/mailcore2-android-4')

4.Add the following code to app/build.gradle of your app. Make sure to change the react-native version 
   properly : 

    import com.android.build.gradle.internal.pipeline.TransformTask
    def deleteDuplicateJniFiles() {
       def files = fileTree("${buildDir}/intermediates/exploded-aar/com.facebook.react/react- 
       native/0.43.3/jni/") {
          include "**/libgnustl_shared.so"
      }
       files.each { it.delete() }
     }

    tasks.withType(TransformTask) { pkgTask ->
      pkgTask.doFirst { deleteDuplicateJniFiles() }
   }

but still i am facing the issue : 
   Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
   > com.android.build.api.transform.TransformException: com.android.builder.packag
   ing.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libgnu
   stl_shared.so

i am using : 
"react": "16.0.0",
 "react-native": "0.51.0",
  build:gradle : 2.3.3',
 compileSdkVersion 25
 buildToolsVersion "25.0.3"

I have cleared my build cache folder. still the issue exists.

**Comment by Selvamhibiz** [comment] 2018-05-06 06:01
Hi @agenthunt,

And also i tried to run your BasicExample. And face an issue : 

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.

**Comment by agenthunt** [comment] 2018-05-06 13:01
I have updated the BasicExample. On the `com.android.build.api.transform.TransformException: com.android.builder.packag
ing.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libgnu
stl_shared.so` . I am not able to reproduce it. It works fine for me. Could you try with a clean build or put up a project that reproduces this error in a repo?

**Comment by Selvamhibiz** [comment] 2018-05-06 17:42
Hi @agenthunt ,
Yes, now the BasicExample is running fine but it is still giving me the same error : 

com.android.build.api.transform.TransformException: com.android.builder.packag
ing.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libgnu
stl_shared.so.

Your android/build.gradle version is 2.2.3 and my android/build.gradle version is 2.3.3 .This may be any issue for the error.

**Comment by agenthunt** [comment] 2018-05-06 22:08
Ah I see. Please use this fix for gradle version 2.3.3
```
android {
...
...
...
...
...
    packagingOptions{
        pickFirst '**/libgnustl_shared.so'
    }
}
```

**Comment by Selvamhibiz** [comment] 2018-05-07 09:53
Yes, after changing the gradle version and packaging options its working now. But when i send email, the recipient mail box is having "Undisclosed recipients"  in the **TO** field instead of having recipient email address. This happens only in android. When i send mail from iOS, it shows the recipient email address. 
![screenshot](https://user-images.githubusercontent.com/19421975/39696200-901f637e-520a-11e8-8b30-a2bb9ec3181f.png)

**Comment by agenthunt** [comment] 2018-05-07 12:16
ok. great. Can we please close this issue and open a separate one so that it is easier to keep track of? Thanks

**Closed** 2018-05-07 12:28 UTC
